export const states = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  // "Assam",
  // "Bihar",
  // "Chhattisgarh",
  // "Goa",
  // "Gujarat",
  // "Haryana",
  // "Himachal Pradesh",
  // "Jharkhand",
  // "Karnataka",
  // "Kerala",
  // "Madhya Pradesh",
  // "Maharashtra",
  // "Manipur",
  // "Meghalaya",
  // "Mizoram",
  // "Nagaland",
  // "Odisha",
  // "Punjab",
  // "Rajasthan",
  // "Sikkim",
  // "Tamil Nadu",
  // "Telangana",
  // "Tripura",
  // "Uttar Pradesh",
  // "Uttarakhand",
  "West Bengal",
];

export const districtsByState = {
  "Andhra Pradesh": [
    "Anantapur",
    "Chittoor",
    "East Godavari",
    "Guntur",
    "Krishna",
    "Kurnool",
    "Nellore",
    "Prakasam",
    "Srikakulam",
    "Visakhapatnam",
    "Vizianagaram",
    "West Godavari",
    "YSR Kadapa",
  ],
  "Arunachal Pradesh": [
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "Lower Subansiri",
    "Kurung Kumey",
    "Upper Subansiri",
    "West Siang",
    "East Siang",
    "Upper Siang",
    "Lower Siang",
    "Lower Dibang Valley",
    "Dibang Valley",
    "Anjaw",
    " Lohit",
    "Namsai",
    "Changlang",
    "Tirap",
  ],
  "West Bengal": [
    "Alipurduar",
    "Bankura",
    "Birbhum",
    "Burdwan",
    "Cooch Behar",
    "Dakshin Dinajpur",
    "Darjeeling",
    "Hooghly",
    "Howrah",
    "Jalpaiguri",
    "Jhargram",
    "Kalimpong",
    "Kolkata",
    "Malda",
    "Murshidabad",
    "Nadia",
    "North 24 Parganas",
    "Paschim Bardhaman",
    "Paschim Medinipur",
    "Purba Bardhaman",
    "Purba Medinipur",
    "Purulia",
    "South 24 Parganas",
    "Uttar Dinajpur",
  ],

  // add more districts by state here
};

export const village_town = {
  Alipurduar: [
    "Alipurduar Court",
    "Falakata",
    "Kalchini",
    "Kumargram",
    "Madarihat",
    "Mainaguri",
    "Rajganj",
    "Samuktala",
    "Satali",
    "Binnaguri",
    "Kodalbasti",
    "Falimari",
    "Kathalguri",
    "Basbari",
    "Jaygaon",
    "Bholardabri",
    "Maruganj",
    "Dhupguri",
    "Shalkumarhat",
    "Kalchini Bazar",
  ],
  Bankura: [
    "Bishnupur",
    "Sonamukhi",
    "Khatra",
    "Indus",
    "Mejia",
    "Beliator",
    "Jayrambati",
    "Chhatna",
    "Patrasayer",
    "Gangajalghati",
    "Simlapal",
    "Barjora",
    "Onda",
    "Taldangra",
    "Joypur",
  ],

  Birbhum: [
    "Suri",
    "Rampurhat",
    "Nalhati",
    "Mohammad Bazar",
    "Sainthia",
    "Labhpur",
    "Bolpur Sriniketan",
    "Mayureswar",
    "Nanoor",
    "Illambazar",
    "Murarai",
    "Khayrasole",
    "Dubrajpur",
    "Tarapith",
    "Kandi",
    "Rajnagar",
    "Mallarpur",
    "Ahmadpur",
    "Lohapur",
    "Suri Serai",
    "Nanur",
    "Parui",
    "Nikolas",
  ],

  Burdwan: [
    "Bardhaman",
    "Guskara",
    "Katwa",
    "Kalna",
    "Durgapur",
    "Memari",
    "Raina",
    "Pandaveswar",
    "Galsi",
    "Jamuria",
    "Mongalkote",
    "Ausgram",
    "Kanksa",
    "Ketugram",
    "Gopalpur",
    "Bhatar",
    "Purbasthali",
    "Manteswar",
    "Mangolkote",
    "Khandaghosh",
    "Faridpur",
    "Raniganj",
    "Srirampur",
    "Kulti",
    "Asansol",
    "Ukhra",
    "Hirapur",
    "Banshra",
  ],

  "Cooch Behar": [
    "Cooch Behar",
    "Dinhata",
    "Mathabhanga",
    "Tufanganj",
    "Sitai",
    "Mekliganj",
    "Toofanganj",
    "Haldibari",
    "Ghoksadanga",
    "Boxirhat",
    "Cooch Behar Sadar",
    "Chilapata",
    "Srirampur",
    "Gitaldaha",
    "Dinhata Municipality",
    "Dinhata I",
    "Dinhata II",
    "Cooch Behar P",
    "Cooch Behar M",
    "Sitalkuchi",
    "Tufanganj - I",
    "Tufanganj - II",
    "Mekhliganj P",
    "Mekhliganj M",
    "Patlakhawa",
    "Bara Kamakhyaguri",
    "Baneswar",
    "Jiranpur",
    "Bamanhat",
    "Srikrishnapur",
    "Bakshirhat",
    "Salkumar - I",
    "Salkumar - II",
    "Dinhata PS",
    "Cooch Behar PS",
    "Mekhliganj PS",
    "Tufanganj PS",
    "Sitalkuchi PS",
    "Toofanganj PS",
    "Mathabhanga PS",
    "Gitaldaha PS",
    "Sitai PS",
  ],
  "Dakshin Dinajpur": [
    "Balurghat",
    "Gangarampur",
    "Kumarganj",
    "Tapan",
    "Hili",
    "Harirampur",
    "Bansihari",
    "Kushmandi",
    "Beltala",
    "Bishalgarh",
    "Chak Bhrigu",
    "Dakshin Bansihari",
    "Dakshin Harirampur",
    "Dhangara",
    "Gopalganj",
    "Jamalpur",
    "Kanchantala",
    "Koraitola",
    "Kshudiram Nagar",
    "Mangalpur",
    "Patiram",
    "Pirganj",
    "Ramkrishnapur",
    "Sarangpur",
    "Sreepur",
    "Tentulia",
    "Uttar Bansihari",
    "Uttar Harirampur",
    "Uttar Ramkrishnapur",
  ],

  Darjeeling: [
    "Darjeeling Pulbazar",
    "Darjeeling Town",
    "Kurseong",
    "Kalimpong",
    "Mirik",
    "Phansidewa",
    "Naxalbari",
    "Matigara",
    "Siliguri",
    "Sukna",
    "Bagdogra",
    "Rangpo",
    "Jorethang",
    "Mangan",
    "Rimbick",
    "Tukdah",
    "Dilaram",
    "Pashupati Fatak",
    "Ranidanga",
    "Sittong",
    "Tindharia",
  ],
  Hooghly: [
    "Chinsurah",
    "Serampore",
    "Singur",
    "Tarakeswar",
    "Arambagh",
    "Khanakul",
    "Pandua",
    "Dhaniakhali",
    "Balagarh",
    "Haripal",
    "Chandannagar",
    "Arambag",
    "Kotulpur",
    "Goghat",
    "Pursurah",
    "Magrahat",
    "Tribeni",
    "Jangipara",
    "Kalna",
    "Polba-Dadpur",
    "Raghunathpur",
    "Bhadreswar",
    "Nabadwip",
    "Ajoy Nagar",
    "Bagnan",
    "Kamarpukur",
    "Jirat",
  ],
  Howrah: [
    "Uluberia",
    "Bally",
    "Howrah",
    "Domjur",
    "Panchla",
    "Jagatballavpur",
    "Amta",
    "Udaynarayanpur",
    "Sankrail",
    "Jagatballabhpur",
    "Jangipara",
    "Shyampur",
    "Bagnan",
    "Magra",
    "Arambagh",
  ],
  Jalpaiguri: [
    "Dhupguri",
    "Mainaguri",
    "Malbazar",
    "Alipurduar",
    "Falakata",
    "Madarihat",
    "Maynaguri",
    "Nagrakata",
    "Rajganj",
    "Jalpaiguri",
    "Matiali",
    "Banarhat",
    "Kalchini",
  ],

  Jhargram: [
    "Jhargram",
    "Binpur II",
    "Sankrail",
    "Jamboni",
    "Binpur I",
    "Gopiballavpur II",
    "Nayagram",
    "Gopiballavpur I",
    "Sarenga",
    "Balarampur",
    "Chandrakona I",
    "Chandrakona II",
    "Garbeta I",
    "Garbeta II",
    "Keshiari",
    "Kharagpur I",
    "Kharagpur II",
  ],
  Kalimpong: [
    "Gorubathan",
    "Kalimpong I",
    "Kalimpong II",
    "Gelseydara",
    "Algarah",
  ],
  Kolkata: [
    "Alipore",
    "Anandapur",
    "Ballygunge",
    "Bansdroni",
    "Barisha",
    "Behala",
    "Beliaghata",
    "Bhowanipore",
    "Bowbazar",
    "Burrabazar",
    "Chitpur",
    "Dhakuria",
    "Dum Dum",
    "Garia",
    "Gariahat",
    "Garden Reach",
    "Haltu",
    "Jadavpur",
    "Jorasanko",
    "Kalighat",
    "Kasba",
    "Kestopur",
    "Khardaha",
    "Kidderpore",
    "Lake",
    "Maniktala",
    "Metiabruz",
    "Mominpur",
    "New Alipore",
    "New Garia",
    "Parnasree Pally",
    "Paschim Putiary",
    "Patuli",
    "Phoolbagan",
    "Rajarhat",
    "Regent Park",
    "Santoshpur",
    "Sealdah",
    "Shyampukur",
    "Sinthi",
    "Sonarpur",
    "Tangra",
    "Tollygunge",
    "Ultadanga",
  ],
  Malda: [
    "Old Malda",
    "Mango",
    "Bamangola",
    "Habibpur",
    "Gazole",
    "Kaliachak I",
    "Kaliachak II",
    "Kaliachak III",
    "Kaliachak IV",
    "English Bazar",
    "Manickchak",
    "Ratua I",
    "Ratua II",
    "Chanchal I",
    "Chanchal II",
  ],
  Murshidabad: [
    "Baharampur",
    "Kandi",
    "Lalbag",
    "Jiaganj Azimganj",
    "Domkal",
    "Beldanga",
    "Raghunathganj",
    "Nabagram",
    "Khargram",
    "Bhagawangola",
    "Murshidabad-Jiaganj",
    "Murshidabad-Jangipur",
  ],
  Nadia: [
    "Krishnanagar",
    "Ranaghat",
    "Kalyani",
    "Nabadwip",
    "Tehatta",
    "Chakdaha",
    "Haringhata",
    "Tehatta-I",
    "Nakashipara",
    "Kaliganj",
    "Krishnaganj",
  ],
  "North 24 Parganas": [
    "Barasat",
    "Basirhat",
    "Barrackpore",
    "Bidhannagar",
    "Bongaon",
    "Habra",
    "Madhyamgram",
    "Rajarhat New Town",
    "Taki",
    "Titagarh",
    "Baduria",
    "Dum Dum",
    "Deganga",
    "Haroa",
    "Hingalganj",
    "Minakhan",
    "Sandeshkhali I",
    "Sandeshkhali II",
  ],
  "Paschim Bardhaman": [
    "Asansol MC",
    "Durgapur MC",
    "Raniganj",
    "Andal",
    "Kulti",
    "Jamuria",
    "Faridpur Durgapur",
    "Barabani",
    "Salanpur",
    "Bansberia",
    "Srirampur",
    "Chandannagar MC",
    "Tarakeswar",
    "Chinsurah-Mogra",
    "Arambagh",
    "Goghat",
    "Balagarh",
    "Pandua",
    "Polba-Dadpur",
    "Guialdanga",
    "Memari",
    "Purbasthali",
    "Katwa",
    "Ketugram",
    "Raina II",
    "Khandaghosh",
    "Ukhra",
    "Patrasayer",
    "Sonamukhi",
    "Bhatar",
    "Ondal",
    "Jamtara",
    "Sanka",
    "Raghunathchak",
    "Neturia",
    "Indpur",
    "Laokona",
    "Jhanjra",
    "Kanksa",
    "Sarpi",
    "Rupnarayanpur",
    "Mangalkot",
    "Barjora",
    "Taldangra",
    "Saltora",
    "Simlapal",
    "Belpahari",
    "Baghmundi",
    "Bandwan",
    "Jamboni",
    "Ranibandh",
    "Bansihari",
    "Harishchandrapur I",
    "Harishchandrapur II",
    "Manikchak",
    "Kaliachak I",
    "Kaliachak II",
    "Kaliachak III",
    "Kaliachak IV",
    "English Bazar",
    "Old Malda",
    "Bamangola",
    "Gazole",
    "Habibpur",
    "Jalangi",
    "Lalgola",
    "Sagardighi",
    "Suti I",
    "Suti II",
  ],

  "Paschim Medinipur": [
    "Medinipur",
    "Kharagpur",
    "Jhargram",
    "Gopiballavpur",
    "Garbeta II",
    "Chandrakona I",
    "Keshiari",
    "Narayangarh",
    "Sabang",
    "Dantan I",
    "Mohanpur",
    "Kharar",
    "Nayagram",
    "Bhagawanpur II",
    "Bishnupur I",
    "Salboni",
    "Chandrakona II",
    "Debra",
    "Garbeta I",
    "Dantan II",
    "Ghatal",
    "Belda",
    "Narayanpur",
    "Gangajalghati",
    "Keshpur",
    "Bishnupur II",
    "Indus",
    "Raipur",
  ],

  "Purba Bardhaman": [
    "Durgapur MC",
    "Asansol MC",
    "Raniganj",
    "Guskara",
    "Jamuria",
    "Pandabeswar",
    "Faridpur Durgapur",
    "Memari",
    "Purbasthali",
    "Kalna",
    "Katwa",
    "Ketugram",
    "Raina II",
    "Bhatar",
    "Khandaghosh",
    "Ukhra",
    "Jamalpur",
    "Ausgram I",
    "Ausgram II",
    "Mangolkote",
    "Kajora",
    "Illambazar",
    "Gopinathpur",
    "Raina I",
    "Paschim Bardhaman",
  ],
  "Purba Medinipur": [
    "Contai",
    "Egra",
    "Haldia",
    "Kanthi",
    "Nandigram",
    "Panskura",
    "Tamluk",
    "Bhagawanpur I",
    "Chandipur",
    "Mahisadal",
    "Moyna",
    "Nandakumar",
    "Patashpur I",
    "Ramnagar I",
    "Khejuri",
    "Bhagawanpur II",
    "Chawalkhola",
    "Kolaghat",
    "Narayangarh",
    "Pingla",
    "Sabang",
    "Sahid Matangini",
    "Sutahata",
    "Dantan I",
    "Debra",
    "Digha",
    "Ramnagar II",
    "Egra I",
    "Egra II",
    "Khejuri II",
    "Mandarmani",
    "Mohanpur",
    "Panskura II",
    "Sutahata II",
  ],

  Purulia: [
    "Adra",
    "Balarampur",
    "Bandwan",
    "Barabazar",
    "Bundwan",
    "Hura",
    "Jaipur",
    "Jhalda I",
    "Jhalda II",
    "Manbazar I",
    "Manbazar II",
    "Puncha",
    "Purulia I",
    "Purulia II",
    "Raghunathpur I",
    "Raghunathpur II",
    "Santuri",
  ],
  "South 24 Parganas": [
    "Alipore",
    "Baruipur",
    "Bhangar I",
    "Bhangar II",
    "Bishnupur",
    "Budge Budge",
    "Canning I",
    "Canning II",
    "Diamond Harbour I",
    "Diamond Harbour II",
    "Falta",
    "Gosaba",
    "Joka",
    "Kakdwip",
    "Kulpi",
    "Magrahat I",
    "Magrahat II",
    "Mandirbazar",
    "Namkhana",
    "Patharpratima",
    "Sagar",
    "Sonarpur",
    "Thakurpukur Mahestala",
  ],
  "Uttar Dinajpur": [
    "Islampur",
    "Raiganj",
    "Goalpokhar I",
    "Goalpokhar II",
    "Chopra",
    "Kaliaganj",
    "Hemtabad",
    "Karandighi",
    "Itahar",
    "Harirampur",
  ],
};
