# Generated by Django 3.2.18 on 2023-05-18 12:58

import RationSystem.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('rationId', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tc', models.BooleanField()),
                ('face_image', models.FileField(upload_to=RationSystem.models.RationUser.user_dir_path)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RationKYC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('houseNo', models.CharField(max_length=99)),
                ('village', models.CharField(max_length=255)),
                ('post_office', models.CharField(max_length=255)),
                ('pin', models.CharField(max_length=6)),
                ('Annual_income', models.CharField(max_length=10)),
                ('aadharcardNo', models.CharField(max_length=14)),
                ('phoneNo', models.CharField(max_length=10)),
                ('dateofbirth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=40)),
                ('district', models.CharField(max_length=40)),
                ('fpsCode', models.CharField(max_length=18)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardType', models.CharField(max_length=30)),
                ('rice', models.CharField(max_length=10)),
                ('wheat', models.CharField(max_length=10)),
                ('oil', models.CharField(max_length=10)),
                ('kerosene', models.CharField(max_length=10)),
                ('nextRationDate', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
